FROM denoland/deno:alpine-1.11.5

# The port that your application listens to.
EXPOSE 3000

WORKDIR /app

# Prefer not to run as root.
USER deno

COPY './import_map.json' .

# These steps will be re-run upon each file change in your working directory:
ADD . .

# Compile the main app so that it doesn't need to be compiled each startup/entry.
# RUN deno cache --unstable mod.tsx
CMD ["run", "--import-map=./import_map.json", "-A", "--unstable", "mod.ts"]